### ISSUE TITLE
Suggestions for MFM

### ISSUE THREAD

**Issue by ChimpGamer** [Zrips/MobFarmManager#2]
Hey there,

I have two suggestions for the Mob Farm Manager plugin.
The first suggestion is to add a command /mfm check (range) to check the amount of entities in the current chunk or in a defined range. (You might wanna limit the range to like 15 or something like that.)
The second suggestion is logging entities that get removed by MFM. Location, entities and the amount of entities (per entity and total). This would be really useful for debuggin.

**Comment by glorying16** [comment]
I came here hoping there was a entity removal log that I just missed enabling. I would love to see this feature added. I recently had a player claim to lose a few named mobs, and tried to look in the server logs for any indication of it being caused by MFM, but found nothing. But since I know this can also be a vanilla bug, it would be great to be able to debug for confirmations. This would also make it easier to track down potential problem areas after the fact.

**Comment by mrfloris** [comment]
I would not mind a 24 hour rolling log file that I can review, I don't need weeks of data. But if we're trying to tweak stuff it would indeed be nice if there's a file to reference as to what happens throughout the day.

in regards to your first suggestion, how's it different from ` /mfm list (range) - List chunks with most entities in them`, which should give a pretty good impression.

**Comment by Zrips** [comment]
Adding and fixing with next version
