### ISSUE TITLE
Armor Stand and ItemFrame limit not working

### ISSUE THREAD

**Issue by TheNylox** [Zrips/MobFarmManager#23]
![111](https://user-images.githubusercontent.com/62629868/131220047-995129ad-61f8-49d4-90fb-c8bcd049fb29.jpg)
![2222](https://user-images.githubusercontent.com/62629868/131220053-04862a5f-9184-46a4-849b-16e661b700ae.jpg)

Server version: git-Tuinity-"f7c4249" (MC 1.16.5)
Mob Farm Manager v 2.0.0.1

**Comment by zSteley** [comment]
Yes, i have the same issue!! 

The issue is that you can bypass the limit of armorstand moving them from one chunk to another! 

For example using water!! 

I want to fix that because some players create lag machines using this.. 


They use a wall to place the armorstands under a stream of water, right next to the adjoining chunk, so the armor stands are moved from chunk to winged and not limited by the plugin. In fact you can place infinities, the last chunk I checked had more than 30k armorstands, I had to remove the world from the server and use an external program to fix the chunk because it was impossible to enter from the game due to the terrible lag it generated. It also creates server crashes when someone loads that particular zone. So it is an important bug that the limitation between chunks is constantly checked and not only when placing the armorstand !!


You can see a video explaining this bypass here: https://www.youtube.com/watch?v=vp26weVppX8 (minute 18:30)

Please fix this ASAP
Thanks!

**Comment by Zrips** [comment]
@TheNylox 
You are trying to use blockTypes list to define entities, armorstands and itemframe limitations are defined in EntityTypes section.

**Comment by zSteley** [comment]
For me the limitations work fine, but it have bypass! @Zrips

**Comment by Zrips** [comment]
@elmaslarry 
offhand click will get fix today. And there was small issue with armor stands being excluded from auto cleanup process. So that one gets a fix too.

**Comment by zSteley** [comment]
Okey Thanks!
